### ISSUE TITLE
angular-in-memory-web-api peer dependency to angular 6

### ISSUE THREAD

**Issue by bjowes** [joeeames/UnitTestingAngularLikeABoss#1]
I have angular 7 installed.

npm install returns:

> npm WARN angular-in-memory-web-api@0.6.1 requires a peer of @angular/common@^6.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN angular-in-memory-web-api@0.6.1 requires a peer of @angular/core@^6.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN angular-in-memory-web-api@0.6.1 requires a peer of @angular/http@^6.0.0 but none is installed. You must install peer dependencies yourself.
> 

I checked but could not find any new release of angular-in-memory-web-api that supports angular 7 (though there are commits indicating it is in the works).

Is the project / workshop fully functional with angular 7 despite these warnings?

Looking forward to Monday!

**Comment by joeeames** [comment]
Yes it should be fine. Try npm start to double check, but it's ok despite
the warnings

**Comment by joeeames** [comment]
yeah, it's fine.
